name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Local docker build (non-root image)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64
          target: release
          build-args: |
            VERSION=latest-dev
            GIT_COMMIT=${{ github.sha }}
            REPO_URL=https://github.com/forge4flow/forge-cli
          load: true
          tags: forge4flow/forge-cli:${{ github.sha }}
      - name: Test for multi-arch build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: false
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          target: release
          build-args: |
            VERSION=latest-dev
            GIT_COMMIT=${{ github.sha }}
            REPO_URL=https://github.com/forge4flow/forge-cli
          tags: forge4flow/forge-cli:${{ github.sha }}
      - name: Copy binary to host
        run: |
          docker create --name forge-cli forge4flow/forge-cli:${{ github.sha }} && \
          mkdir -p ./bin && \
          docker cp forge-cli:/usr/bin/forge-cli ./bin && \
          docker rm -f forge-cli
      - name: Build samples
        run: ./build_samples.sh
      - name: Test version
        run: ./test/version.sh ./bin/forge-cli
        # TODO: Fix testing
        # - name: Test the cli and the function behaviour
        #   run: make test-templating
